#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set designated workspaces to specific programs (custom)
#firefox/qutebrowser/brave
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a brave desktop='^9'
#vscode
bspc rule -a code desktop='^3'
#pulseaudio volume
bspc rule -a pavucontrol desktop='^4'
#spotify
bspc rule -a spotify desktop=^'^8'



################################################################################
# custom configuration for nord rice :)
################################################################################

# border colors
bspc config normal_border_color "#d8dee9"
bspc config active_border_color "#d8dee9"

# initiate picom
picom &
# polybar config use option <--themes> to list all
zsh /home/cyph4/.config/polybar/launch.sh --shapes

# set wallpaper
feh --bg-scale /home/cyph4/Desktop/Stuff/nord1.png



# temp rules (remove after testing)
